'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Reports.Visualizers.Excel
    
    Partial Public Class Visualizer
        
        '''<summary>
        '''grdResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdResults As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''cmdExportToExcel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdExportToExcel As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imgExcelGraphic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgExcelGraphic As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''lblExportToExcel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExportToExcel As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
